### ISSUE TITLE
Difference between Interface and Abstract class? 

### ISSUE THREAD

**Issue by Urunov** [Urunov/Interview-Integrity-toAnyCompany#1]

**Comment by Urunov** [comment]
1. OOP concept.

**Comment by Azodov** [comment]
Classes created with the abstract keyword are called abstract classes. Abstract classes consist of abstract methods (methods without a body) or non-abstract methods (methods with a body).

**Comment by Azodov** [comment]
An abstract class and abstract method is declared as follows:
abstract class Radio{  
  abstract void live();  
}  
  
class Status extends Radio{  
void now(){System.out.println("Ishlamoqda...");}  
  
public static void main(String args[]){  
 Radio obj = new Status();  
 obj.now();  
}  
}

**Comment by Urunov** [comment]
Java OOP and Project
